# Generated by Django 4.2.16 on 2024-09-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Item name')),
                ('brand', models.CharField(max_length=128, null=True, verbose_name='Item brand')),
                ('model', models.CharField(max_length=128, null=True, verbose_name='Item model')),
                ('description', models.CharField(max_length=512, null=True, verbose_name='Item description')),
            ],
            options={
                'db_table': 'items',
                'managed': True,
            },
        ),
    ]
