# Generated by Django 4.2.16 on 2024-11-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_items_category_items_stock_quantity_items_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.CharField(default=None, max_length=4096, null=True, verbose_name='Item Image'),
        ),
    ]
