# Generated by Django 4.2.16 on 2024-10-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Item name')),
                ('brand', models.CharField(default=None, max_length=128, null=True, verbose_name='Item brand')),
                ('model', models.CharField(default=None, max_length=128, null=True, verbose_name='Item model')),
                ('description', models.CharField(default=None, max_length=512, verbose_name='Item description')),
                ('value', models.DecimalField(decimal_places=4, default=None, max_digits=20, verbose_name='Item value')),
                ('quantity', models.BigIntegerField(verbose_name='Quantity field')),
                ('user', models.BigIntegerField(verbose_name='User ID field')),
            ],
            options={
                'db_table': 'sales',
                'managed': True,
            },
        ),
    ]
