# Generated by Django 4.2.16 on 2024-10-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('itemname', models.CharField(default='', max_length=256)),
                ('itemdescription', models.CharField(default='', max_length=512)),
                ('itemvalue', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('salequantity', models.IntegerField(default=0)),
                ('salevalue', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('saledate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
